import ReduxProvider from '@/providers/ReduxProvider'
import { ToastifyProvider } from '@packages/shared'
import type { Metadata } from 'next'
import './page.css'

export const metadata: Metadata = {
	title: 'Admin panel',
	description: 'Generated by create next app',
}

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode
}>) => (
	<html lang='en'>
		<body>
			<ReduxProvider>
				<ToastifyProvider />
				{children}
			</ReduxProvider>
		</body>
	</html>
)

export default RootLayout
