import {
	AWS,
	CSS,
	ESLint,
	Figma,
	Git,
	GitHub,
	GithubActions,
	GraphQL,
	HookForm,
	HTML,
	Insomnia,
	JavaScript,
	MongoDB,
	MUI,
	NestJS,
	NextJS,
	NodeJS,
	Postman,
	Prettier,
	React,
	Redux,
	Sass,
	Scss,
	Socket,
	Styled,
	Tailwind,
	TypeScript,
	Vite,
	VSCode,
	Webpack,
	WebStorm,
} from '../../../../../public/icons'

export interface Skill {
	name: string
	category: string
	icon: React.ElementType
}

export const SKILLS: Skill[] = [
	{
		icon: HTML,
		category: 'basic',
		name: 'HTML',
	},
	{ icon: CSS, category: 'ui', name: 'CSS' },
	{ icon: JavaScript, category: 'basic', name: 'JavaScript' },
	{ icon: TypeScript, category: 'basic', name: 'TypeScript' },
	{ icon: React, category: 'basic', name: 'React.js' },
	{ icon: NextJS, category: 'basic', name: 'Next.js' },
	{ icon: Redux, category: 'basic', name: 'Redux Toolkit' },
	{ icon: NodeJS, category: 'backend', name: 'Node.js' },
	{ icon: NestJS, category: 'backend', name: 'Nest.js' },
	{ icon: AWS, category: 'backend', name: 'AWS' },
	{ icon: MongoDB, category: 'backend', name: 'MongoDB' },
	{ icon: Tailwind, category: 'ui', name: 'Tailwind CSS' },
	{ icon: Sass, category: 'ui', name: 'Sass' },
	{ icon: Scss, category: 'ui', name: 'Scss' },
	{ icon: GraphQL, category: 'backend', name: 'GraphQL' },
	{ icon: Prettier, category: 'tools', name: 'Prettier' },
	{ icon: ESLint, category: 'tools', name: 'ESLint' },
	{ icon: Webpack, category: 'basic', name: 'Webpack' },
	{ icon: MUI, category: 'ui', name: 'MUI' },
	{ icon: Git, category: 'tools', name: 'Git' },
	{ icon: GitHub, category: 'tools', name: 'GitHub' },
	{ icon: Insomnia, category: 'backend', name: 'Insomnia' },
	{ icon: Postman, category: 'backend', name: 'Postman' },
	{ icon: WebStorm, category: 'tools', name: 'WebStorm' },
	{ icon: VSCode, category: 'tools', name: 'VSCode' },
	{ icon: Figma, category: 'tools', name: 'Figma' },
	{ icon: Styled, category: 'ui', name: 'Styled Components' },
	{ icon: Socket, category: 'backend', name: 'Socket.io' },
	{ icon: GithubActions, category: 'tools', name: 'Github Actions' },
	{ icon: Vite, category: 'basic', name: 'Vite' },
	{ icon: HookForm, category: 'ui', name: 'React Hook Form' },
]
