import {
	AWS,
	CSS,
	ESLint,
	Figma,
	Git,
	GitHub,
	GithubActions,
	GraphQL,
	HTML,
	Insomnia,
	JavaScript,
	MongoDB,
	MUI,
	NestJS,
	NextJS,
	NodeJS,
	Postman,
	Prettier,
	React,
	Redux,
	Sass,
	Scss,
	Socket,
	Styled,
	Tailwind,
	TypeScript,
	VSCode,
	Webpack,
	WebStorm,
} from '../../../../../public/icons'

interface Skill {
	icon: React.ElementType
	category: string
}
export type SkillsCategoryTypes = 'all' | 'language' | 'styling' | 'tools'

export const SKILLS: Skill[] = [
	{ icon: HTML, category: 'language' },
	{ icon: CSS, category: 'styling' },
	{ icon: JavaScript, category: 'language' },
	{ icon: TypeScript, category: 'language' },
	{ icon: React, category: '' },
	{ icon: NextJS, category: '' },
	{ icon: Redux, category: '' },
	{ icon: NodeJS, category: '' },
	{ icon: NestJS, category: '' },
	{ icon: AWS, category: '' },
	{ icon: MongoDB, category: '' },
	{ icon: Tailwind, category: 'styling' },
	{ icon: Sass, category: 'styling' },
	{ icon: Scss, category: 'styling' },
	{ icon: GraphQL, category: '' },
	{ icon: Prettier, category: 'tools' },
	{ icon: ESLint, category: 'tools' },
	{ icon: Webpack, category: '' },
	{ icon: MUI, category: '' },
	{ icon: Git, category: 'tools' },
	{ icon: GitHub, category: 'tools' },
	{ icon: Insomnia, category: 'tools' },
	{ icon: Postman, category: 'tools' },
	{ icon: WebStorm, category: 'tools' },
	{ icon: VSCode, category: 'tools' },
	{ icon: Figma, category: 'tools' },
	{ icon: Styled, category: 'styling' },
	{ icon: Socket, category: 'tools' },
	{ icon: GithubActions, category: 'tools' },
]
